name: No Caching Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  no-caching-tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: false
      solana_version: 3.0.0
      node_version: 20.18.0
      cargo_profile: release
      anchor_binary_name: anchor-binary-no-caching
      surfpool_cli_version: 0.11.2
